### ISSUE TITLE
Generate JSON for form data

### ISSUE THREAD

**Issue by pratik-pato** [vaishnavi0393/form#1]
Refer below json object
`{
	"identity_details":{
		"name":"",
		"gender":"",
		"marital_status":"",
		"dob":"",
		"nationality":"",
		"status":"",
		"PAN_number":"",
		"aadhar_number":""
	},
	"address_details":{
		"permanent_address":"",
		"communication_address":"",
		"contact_number":"",
		"email":""
	},
	"other_information":{
		"gross_annual_income":"",
		"occupation":"",
		"applicable_type":"",
		"KYC_check":""
	},
	"investment_profile":{
		"investment_experience_in_security":"",
		"investment_goals":"",
		"risk_tolerance":"",
		"investment_objectives":""
	}
}`

**Comment by vaishnavi0393** [comment]
JSON object created.
